/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-02-14 03:44:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DynamicTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-us\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>Datatables User</title>\r\n");
      out.write("      \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"/> \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css\"/> \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/buttons/1.1.2/css/buttons.dataTables.min.css\"/> \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/select/1.1.2/css/select.dataTables.min.css\"/>\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/responsive/2.0.2/css/responsive.dataTables.min.css\"/> \r\n");
      out.write("      \r\n");
      out.write("      <style>\r\n");
      out.write("        table.dataTable tbody>tr.selected,\r\n");
      out.write("        table.dataTable tbody>tr>.selected {\r\n");
      out.write("          background-color: #A2D3F6;\r\n");
      out.write("        }\r\n");
      out.write("      </style>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"dataTable table table-striped\" id=\"example\">\r\n");
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"js/altEditor/dataTables.altEditor.free.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/buttons/1.1.2/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/select/1.1.2/js/dataTables.select.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("        var dataSet = [\r\n");
      out.write("          [\"Tiger Nixon\", \"System Architect\", \"Edinburgh\", \"5421\", \"2011/04/25\", \"$320,800\"],\r\n");
      out.write("          [\"Garrett Winters\", \"Accountant\", \"Tokyo\", \"8422\", \"2011/07/25\", \"$170,750\"],\r\n");
      out.write("          [\"Ashton Cox\", \"Junior Technical Author\", \"San Francisco\", \"1562\", \"2009/01/12\", \"$86,000\"],\r\n");
      out.write("          [\"Cedric Kelly\", \"Senior Javascript Developer\", \"Edinburgh\", \"6224\", \"2012/03/29\", \"$433,060\"],\r\n");
      out.write("          [\"Airi Satou\", \"Accountant\", \"Tokyo\", \"5407\", \"2008/11/28\", \"$162,700\"],\r\n");
      out.write("          [\"Brielle Williamson\", \"Integration Specialist\", \"New York\", \"4804\", \"2012/12/02\", \"$372,000\"],\r\n");
      out.write("          [\"Herrod Chandler\", \"Sales Assistant\", \"San Francisco\", \"9608\", \"2012/08/06\", \"$137,500\"],\r\n");
      out.write("          [\"Rhona Davidson\", \"Integration Specialist\", \"Tokyo\", \"6200\", \"2010/10/14\", \"$327,900\"],\r\n");
      out.write("          [\"Colleen Hurst\", \"Javascript Developer\", \"San Francisco\", \"2360\", \"2009/09/15\", \"$205,500\"],\r\n");
      out.write("          [\"Sonya Frost\", \"Software Engineer\", \"Edinburgh\", \"1667\", \"2008/12/13\", \"$103,600\"],\r\n");
      out.write("          [\"Jena Gaines\", \"Office Manager\", \"London\", \"3814\", \"2008/12/19\", \"$90,560\"],\r\n");
      out.write("          [\"Quinn Flynn\", \"Support Lead\", \"Edinburgh\", \"9497\", \"2013/03/03\", \"$342,000\"],\r\n");
      out.write("          [\"Charde Marshall\", \"Regional Director\", \"San Francisco\", \"6741\", \"2008/10/16\", \"$470,600\"],\r\n");
      out.write("          [\"Haley Kennedy\", \"Senior Marketing Designer\", \"London\", \"3597\", \"2012/12/18\", \"$313,500\"],\r\n");
      out.write("          [\"Tatyana Fitzpatrick\", \"Regional Director\", \"London\", \"1965\", \"2010/03/17\", \"$385,750\"],\r\n");
      out.write("          [\"Michael Silva\", \"Marketing Designer\", \"London\", \"1581\", \"2012/11/27\", \"$198,500\"]\r\n");
      out.write("        ];\r\n");
      out.write("\r\n");
      out.write("        var columnDefs = [{\r\n");
      out.write("          title: \"Name\"\r\n");
      out.write("        }, {\r\n");
      out.write("          title: \"Username\"\r\n");
      out.write("        }, {\r\n");
      out.write("          title: \"Password\"\r\n");
      out.write("        }, {\r\n");
      out.write("          title: \"Type.\"\r\n");
      out.write("        }, {\r\n");
      out.write("          title: \"Start date\"\r\n");
      out.write("        }, {\r\n");
      out.write("          title: \"Status\"\r\n");
      out.write("        }];\r\n");
      out.write("\r\n");
      out.write("        var myTable;\r\n");
      out.write("\r\n");
      out.write("        myTable = $('#example').DataTable({\r\n");
      out.write("          \"sPaginationType\": \"full_numbers\",\r\n");
      out.write("          data: dataSet,\r\n");
      out.write("          columns: columnDefs,\r\n");
      out.write("          dom: 'Bfrtip',        // Needs button container\r\n");
      out.write("          select: 'single',\r\n");
      out.write("          responsive: true,\r\n");
      out.write("          altEditor: true,     // Enable altEditor\r\n");
      out.write("          buttons: [{\r\n");
      out.write("            text: 'Add',\r\n");
      out.write("            name: 'add'        // do not change name\r\n");
      out.write("          },\r\n");
      out.write("          {\r\n");
      out.write("            extend: 'selected', // Bind to Selected row\r\n");
      out.write("            text: 'Edit',\r\n");
      out.write("            name: 'edit'        // do not change name\r\n");
      out.write("          },\r\n");
      out.write("          {\r\n");
      out.write("            extend: 'selected', // Bind to Selected row\r\n");
      out.write("            text: 'Delete',\r\n");
      out.write("            name: 'delete'      // do not change name\r\n");
      out.write("         }]\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
